### About Plotly

Plotly is a Data Viz library by the company Plotly based out of Canada with support in languages such as Python, Js, Julia etc.

#### Advantages

- Multi language support
- Lot's of graphs
- Interactive plots
- Beautiful plots

Does not work with live data streams. Dash can be explored for that.

### The Plotly Roadmap

- Plotly Go
- Plotly Express
- Dash

### Working with Plotly Go

In [121]:
# import the libraries
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import plotly.express as px

In [122]:
# import datasets
tips=px.data.tips()
iris=px.data.iris()
gap=px.data.gapminder()

In [123]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [124]:
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [125]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [126]:
# scatter plot using plotly go
temp_df=gap[gap['year']==2007]
temp_df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
...,...,...,...,...,...,...,...,...
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704
1667,West Bank and Gaza,Asia,2007,73.422,4018332,3025.349798,PSE,275
1679,"Yemen, Rep.",Asia,2007,62.698,22211743,2280.769906,YEM,887
1691,Zambia,Africa,2007,42.384,11746035,1271.211593,ZMB,894
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [127]:
trace1=go.Scatter(x=temp_df['lifeExp'],y=temp_df['gdpPercap'],mode='markers')

data=[trace1]

layout=go.Layout(title='life Exp vs GDP per capita for 2007',xaxis={'title':'life exp'},yaxis={'title':'gdp'})
fig=go.Figure(data,layout)
fig.show()

In [128]:
trace1=go.Scatter(x=temp_df['lifeExp'],y=temp_df['gdpPercap'],mode='markers')
trace2=go.Scatter(x=[0,1,2],y=[0,99999,300000],mode='lines')
data=[trace1,trace2]

layout=go.Layout(title='life Exp vs GDP per capita for 2007',xaxis={'title':'life exp'},yaxis={'title':'gdp'})
fig=go.Figure(data,layout)
fig.show()

In [129]:
# plot life exp and gdp scatter plot -> continent as color -> pop as size -> hover name -> range_x/range_y -> log_x/log_y
px.scatter(temp_df,x='lifeExp',y='gdpPercap')

In [130]:
px.scatter(temp_df,x='lifeExp',y='gdpPercap',color='continent')

In [131]:
px.scatter(temp_df,x='lifeExp',y='gdpPercap',color='continent',size='pop')

In [132]:
px.scatter(temp_df,x='lifeExp',y='gdpPercap',color='continent',size='pop',size_max=50)

In [133]:
px.scatter(temp_df,x='lifeExp',y='gdpPercap',color='continent',size='pop',size_max=50,hover_name='country')

In [134]:
# plot animation of the above curve on the basic of year
px.scatter(gap,x='lifeExp',y='gdpPercap',color='continent',size='pop',size_max=50,animation_frame='year',animation_group='country')

In [135]:
px.scatter(gap,x='lifeExp',y='gdpPercap',color='continent',size='pop',size_max=50,range_x=[30,95],animation_frame='year',animation_group='country')

In [136]:
# line plot
# plot india pop line plot
temp_df=gap[gap['country']=='India']

px.line(temp_df,x='year',y='pop',title='India pop growth')

In [137]:
# plot india china pak line plot
temp_df=gap[gap['country'].isin(['India','China','Pakistan']) ]

px.line(temp_df,x='year',y='pop',title='country pop growth',color='country')

In [138]:
px.line(temp_df,x='year',y='lifeExp',title='country pop growth',color='country')

In [139]:
gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='lifeExp').melt()

     country     value
0      China  44.00000
1      China  50.54896
2      China  44.50136
3      China  58.38112
4      China  63.11888
5      China  63.96736
6      China  65.52500
7      China  67.27400
8      China  68.69000
9      China  70.42600
10     China  72.02800
11     China  72.96100
12     India  37.37300
13     India  40.24900
14     India  43.60500
15     India  47.19300
16     India  50.65100
17     India  54.20800
18     India  56.59600
19     India  58.55300
20     India  60.22300
21     India  61.76500
22     India  62.87900
23     India  64.69800
24  Pakistan  43.43600
25  Pakistan  45.55700
26  Pakistan  47.67000
27  Pakistan  49.80000
28  Pakistan  51.92900
29  Pakistan  54.04300
30  Pakistan  56.15800
31  Pakistan  58.24500
32  Pakistan  60.83800
33  Pakistan  61.81800
34  Pakistan  63.61000
35  Pakistan  65.48300

In [140]:
temp_df=gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='lifeExp')
temp_df

country     China   India  Pakistan
year
1952     44.00000  37.373    43.436
1957     50.54896  40.249    45.557
1962     44.50136  43.605    47.670
1967     58.38112  47.193    49.800
1972     63.11888  50.651    51.929
1977     63.96736  54.208    54.043
1982     65.52500  56.596    56.158
1987     67.27400  58.553    58.245
1992     68.69000  60.223    60.838
1997     70.42600  61.765    61.818
2002     72.02800  62.879    63.610
2007     72.96100  64.698    65.483

In [141]:
px.line(temp_df,x=temp_df.index,y=temp_df.columns)

In [142]:
# bar chart
# india's pop over the years
temp_df=gap[gap['country']=='India']
temp_df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
696,India,Asia,1952,37.373,372000000,546.565749,IND,356
697,India,Asia,1957,40.249,409000000,590.061996,IND,356
698,India,Asia,1962,43.605,454000000,658.347151,IND,356
699,India,Asia,1967,47.193,506000000,700.770611,IND,356
700,India,Asia,1972,50.651,567000000,724.032527,IND,356
701,India,Asia,1977,54.208,634000000,813.337323,IND,356
702,India,Asia,1982,56.596,708000000,855.723538,IND,356
703,India,Asia,1987,58.553,788000000,976.512676,IND,356
704,India,Asia,1992,60.223,872000000,1164.406809,IND,356
705,India,Asia,1997,61.765,959000000,1458.817442,IND,356
706,India,Asia,2002,62.879,1034172547,1746.769454,IND,356
707,India,Asia,2007,64.698,1110396331,2452.210407,IND,356

In [143]:
px.bar(temp_df,x='year',y='pop')

In [144]:
# pop comp of 3 countries
temp_df=gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='gdpPercap')
temp_df

country        China        India     Pakistan
year
1952      400.448611   546.565749   684.597144
1957      575.987001   590.061996   747.083529
1962      487.674018   658.347151   803.342742
1967      612.705693   700.770611   942.408259
1972      676.900092   724.032527  1049.938981
1977      741.237470   813.337323  1175.921193
1982      962.421381   855.723538  1443.429832
1987     1378.904018   976.512676  1704.686583
1992     1655.784158  1164.406809  1971.829464
1997     2289.234136  1458.817442  2049.350521
2002     3119.280896  1746.769454  2092.712441
2007     4959.114854  2452.210407  2605.947580

In [145]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns)

In [146]:
# grouped bar chart -> text_auto
px.bar(temp_df,x=temp_df.index,y=temp_df.columns,barmode='group')

In [147]:
temp_df=gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='pop')
temp_df

country       China       India   Pakistan
year
1952      556263527   372000000   41346560
1957      637408000   409000000   46679944
1962      665770000   454000000   53100671
1967      754550000   506000000   60641899
1972      862030000   567000000   69325921
1977      943455000   634000000   78152686
1982     1000281000   708000000   91462088
1987     1084035000   788000000  105186881
1992     1164970000   872000000  120065004
1997     1230075000   959000000  135564834
2002     1280400000  1034172547  153403524
2007     1318683096  1110396331  169270617

In [148]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns,barmode='group')

In [149]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns,barmode='group',log_y=True)

In [150]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns,barmode='group',log_y=True,text_auto=True)

In [151]:
# stacked bar chart
# pop contribution per country to a continents pop stacked for a particular year(2007)
temp_df=gap[gap['year']==2007]
px.bar(temp_df,x='continent',y='pop',color='country')

In [152]:
px.bar(temp_df,x='continent',y='pop',color='country',log_y=True)

In [153]:
# bar chart animation
px.bar(gap,x='continent',y='pop',color='continent',animation_frame='year',animation_group='country')

In [154]:
px.bar(gap,x='continent',y='pop',color='continent',animation_frame='year',animation_group='country',range_y=(0,4000000000))

In [155]:
# histogram
# plot histogram of life expt of all countries in 2007 -> nbins -> text_auto
temp_df=gap[gap['year']==2007]
px.histogram(temp_df,x='lifeExp')

In [156]:
px.histogram(temp_df,x='lifeExp',nbins=30,text_auto=True)

In [157]:
# plot histogram of sepal length of all iris species
px.histogram(iris,x='sepal_length')

In [158]:
px.histogram(iris,x='sepal_length',color='species')

In [159]:
px.histogram(iris,x='sepal_length',color='species',nbins=30,text_auto=True)

In [160]:
# Pie -> values -> names
# find the pie chart of pop of european countries in 2007
temp_df=gap[(gap['year']==2007) & (gap['continent']=='Europe')]

px.pie(temp_df,values='pop',names='country')

In [161]:
px.pie(temp_df,values='pop',names='country')

In [162]:
# plot pie chart of world pop in 1952 continent wise ->  -> explode(pull)
temp_df=gap[gap['year']==1952].groupby('continent')['pop'].sum().reset_index()

px.pie(temp_df,values='pop',names='continent')

In [163]:
# Sunburst plot -> Sunburst plots visualize hierarchical data spanning outwards radially from root to leaves. -> color
# path -> [], values

temp_df=gap[gap['year']==2007]
px.sunburst(temp_df,path=['continent','country'],values='pop')

In [164]:
temp_df=gap[gap['year']==2007]
px.sunburst(temp_df,path=['continent','country'],values='pop',color='lifeExp')

In [165]:
px.sunburst(tips,path=['sex','smoker','day','time'],values='total_bill',color='size')

In [166]:
# Treemap
temp_df=gap[gap['year']==2007]

px.treemap(temp_df,path=[px.Constant('World'),'continent','country'],values='pop',color='lifeExp')

In [167]:
# Heatmap -> find heatmap of all continents with year on avg life exp
temp_df = tips.pivot_table(index='day',columns='sex',values='total_bill',aggfunc='sum')
px.imshow(temp_df)

In [168]:
temp_df=gap.pivot_table(index='year',columns='continent',values='lifeExp',aggfunc='mean')

px.imshow(temp_df)

In [169]:
# 3d scatterplot
# plot a 3d scatter plot of all country data for 2007

temp_df=gap[gap['year']==2007]

px.scatter_3d(temp_df,x='lifeExp',y='pop',z='gdpPercap',log_y=True)

In [170]:
px.scatter_3d(temp_df,x='lifeExp',y='pop',z='gdpPercap',log_y=True,color='continent')

In [171]:
px.scatter_3d(iris,x='sepal_length',y='sepal_width',z='petal_length',color='species')

In [172]:
# scatter_matrix -> dimensions
px.scatter_matrix(iris,dimensions=['sepal_length','sepal_width','petal_length','petal_width'],color='species')

In [43]:
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

In [44]:
# facet plot
tips=px.data.tips()
gap=px.data.gapminder()

In [45]:
px.scatter(tips,x='total_bill',y='tip')

In [46]:
px.scatter(tips,x='total_bill',y='tip',facet_col='sex')

In [47]:
px.scatter(tips,x='total_bill',y='tip',facet_col='day')

In [48]:
px.scatter(tips,x='total_bill',y='tip',facet_col='smoker')

In [49]:
px.scatter(tips,x='total_bill',y='tip',facet_col='smoker',facet_row='sex')

In [50]:
px.histogram(tips,x='total_bill',facet_col='sex')

In [51]:
temp_df=gap[gap['country']=='India']

px.scatter(temp_df,x='lifeExp',y='gdpPercap',facet_col='year')

In [52]:
px.scatter(gap,x='lifeExp',y='gdpPercap',facet_col='year')

In [53]:
px.scatter(gap,x='lifeExp',y='gdpPercap',facet_col='year',facet_col_wrap=3)

In [54]:
# 3d Surface plot
# can not be created using Plotly express
# we will use plotly graph object -> go

x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)

z = xx**2 + yy**2

In [55]:
trace=go.Surface(x=x,y=y,z=z)
data=[trace]
layout=go.Layout(title='3D surface plot')
fig=go.Figure(data,layout)
fig.show()

In [56]:
z = np.sin(xx)+np.cos(yy)
trace=go.Surface(x=x,y=y,z=z)
data=[trace]
layout=go.Layout(title='3D surface plot')
fig=go.Figure(data,layout)
fig.show()

In [57]:
z = np.sin(xx)+np.tan(yy)
trace=go.Surface(x=x,y=y,z=z)
data=[trace]
layout=go.Layout(title='3D surface plot')
fig=go.Figure(data,layout)
fig.show()

In [59]:
# Contour plot
x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)

In [60]:
z=xx**2+yy**2

trace=go.Contour(x=x,y=y,z=z)
data=[trace]
layout=go.Layout(title='3D surface plot')
fig=go.Figure(data,layout)
fig.show()

In [61]:
# Subplots
from plotly.subplots import make_subplots

In [62]:
fig=make_subplots(rows=1,cols=2)

In [63]:
fig.add_trace(
     go.Scatter(x=[1,9,5],y=[2,10,1]),
     row=1,
     col=1
)
fig.add_trace(
     go.Histogram(x=[1,9,22,100,109,134,56,78]),
     row=1,
     col=2
)
fig.update_layout(title='subplot Demo')

In [64]:
fig=make_subplots(rows=2,cols=2)

In [65]:
fig.add_trace(
     go.Scatter(x=[1,9,5],y=[2,10,1]),
     row=1,
     col=1
)
fig.add_trace(
     go.Histogram(x=[1,9,22,100,109,134,56,78]),
     row=1,
     col=2
)
fig.add_trace(
     go.Scatter(x=[1,9,5],y=[2,10,1],mode='markers'),
     row=2,
     col=1
)
fig.add_trace(
     go.Histogram(x=[1,9,22,100,109,134,56,78]),
     row=2,
     col=2
)
fig.update_layout(title='subplot Demo')