In [1]:
import pandas as pd
import numpy as np

In [2]:
latlong=pd.read_csv('district wise centroids.csv')
latlong.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [3]:
latlong.shape

(594, 4)

In [4]:
latlong.isnull().sum()

State        0
District     0
Latitude     0
Longitude    0
dtype: int64

In [5]:
latlong.duplicated().sum()

np.int64(0)

In [6]:
census=pd.read_csv('india-districts-census-2011.csv')
census.head()

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629

In [7]:
census.shape

(640, 118)

In [8]:
census.duplicated().sum()

np.int64(0)

In [9]:
census.isnull().sum()

District code                    0
State name                       0
District name                    0
Population                       0
Male                             0
                                ..
Power_Parity_Rs_330000_425000    0
Power_Parity_Rs_425000_545000    0
Power_Parity_Rs_330000_545000    0
Power_Parity_Above_Rs_545000     0
Total_Power_Parity               0
Length: 118, dtype: int64

In [10]:
census.columns.to_list()

['District code',
 'State name',
 'District name',
 'Population',
 'Male',
 'Female',
 'Literate',
 'Male_Literate',
 'Female_Literate',
 'SC',
 'Male_SC',
 'Female_SC',
 'ST',
 'Male_ST',
 'Female_ST',
 'Workers',
 'Male_Workers',
 'Female_Workers',
 'Main_Workers',
 'Marginal_Workers',
 'Non_Workers',
 'Cultivator_Workers',
 'Agricultural_Workers',
 'Household_Workers',
 'Other_Workers',
 'Hindus',
 'Muslims',
 'Christians',
 'Sikhs',
 'Buddhists',
 'Jains',
 'Others_Religions',
 'Religion_Not_Stated',
 'LPG_or_PNG_Households',
 'Housholds_with_Electric_Lighting',
 'Households_with_Internet',
 'Households_with_Computer',
 'Rural_Households',
 'Urban_Households',
 'Households',
 'Below_Primary_Education',
 'Primary_Education',
 'Middle_Education',
 'Secondary_Education',
 'Higher_Education',
 'Graduate_Education',
 'Other_Education',
 'Literate_Education',
 'Illiterate_Education',
 'Total_Education',
 'Age_Group_0_29',
 'Age_Group_30_49',
 'Age_Group_50',
 'Age not stated',
 'Households_with_Bicycle',
 'Households_with_Car_Jeep_Van',
 'Households_with_Radio_Transistor',
 'Households_with_Scooter_Motorcycle_Moped',
 'Households_with_Telephone_Mobile_Phone_Landline_only',
 'Households_with_Telephone_Mobile_Phone_Mobile_only',
 'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car',
 'Households_with_Television',
 'Households_with_Telephone_Mobile_Phone',
 'Households_with_Telephone_Mobile_Phone_Both',
 'Condition_of_occupied_census_houses_Dilapidated_Households',
 'Households_with_separate_kitchen_Cooking_inside_house',
 'Having_bathing_facility_Total_Households',
 'Having_latrine_facility_within_the_premises_Total_Households',
 'Ownership_Owned_Households',
 'Ownership_Rented_Households',
 'Type_of_bathing_facility_Enclosure_without_roof_Households',
 'Type_of_fuel_used_for_cooking_Any_other_Households',
 'Type_of_latrine_facility_Pit_latrine_Households',
 'Type_of_latrine_facility_Other_latrine_Households',
 'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households',
 'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households',
 'Not_having_bathing_facility_within_the_premises_Total_Households',
 'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households',
 'Main_source_of_drinking_water_Un_covered_well_Households',
 'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households',
 'Main_source_of_drinking_water_Spring_Households',
 'Main_source_of_drinking_water_River_Canal_Households',
 'Main_source_of_drinking_water_Other_sources_Households',
 'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households',
 'Location_of_drinking_water_source_Near_the_premises_Households',
 'Location_of_drinking_water_source_Within_the_premises_Households',
 'Main_source_of_drinking_water_Tank_Pond_Lake_Households',
 'Main_source_of_drinking_water_Tapwater_Households',
 'Main_source_of_drinking_water_Tubewell_Borehole_Households',
 'Household_size_1_person_Households',
 'Household_size_2_persons_Households',
 'Household_size_1_to_2_persons',
 'Household_size_3_persons_Households',
 'Household_size_3_to_5_persons_Households',
 'Household_size_4_persons_Households',
 'Household_size_5_persons_Households',
 'Household_size_6_8_persons_Households',
 'Household_size_9_persons_and_above_Households',
 'Location_of_drinking_water_source_Away_Households',
 'Married_couples_1_Households',
 'Married_couples_2_Households',
 'Married_couples_3_Households',
 'Married_couples_3_or_more_Households',
 'Married_couples_4_Households',
 'Married_couples_5__Households',
 'Married_couples_None_Households',
 'Power_Parity_Less_than_Rs_45000',
 'Power_Parity_Rs_45000_90000',
 'Power_Parity_Rs_90000_150000',
 'Power_Parity_Rs_45000_150000',
 'Power_Parity_Rs_150000_240000',
 'Power_Parity_Rs_240000_330000',
 'Power_Parity_Rs_150000_330000',
 'Power_Parity_Rs_330000_425000',
 'Power_Parity_Rs_425000_545000',
 'Power_Parity_Rs_330000_545000',
 'Power_Parity_Above_Rs_545000',
 'Total_Power_Parity']

In [11]:
cols=['District code','District name', 'Population','Male','Female','Literate','Male_Literate','Female_Literate','Housholds_with_Electric_Lighting','Households_with_Internet']

In [12]:
cols=['District code','District name', 'Population','Male','Female','Literate','Male_Literate','Female_Literate','Housholds_with_Electric_Lighting','Households_with_Internet']

In [13]:
census=census[cols]
census.head()

,District code,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet
0,1,Kupwara,870354,474190,396164,439654,282823,156831,83071,762
1,2,Badgam,753745,398041,355704,335649,207741,127908,90190,1999
2,3,Leh(Ladakh),133487,78971,54516,93770,62834,30936,17250,574
3,4,Kargil,140802,77785,63017,86236,56301,29935,15824,235
4,5,Punch,476835,251899,224936,261724,163333,98391,62900,346

In [14]:
final_df=latlong.merge(census,left_on='District',right_on='District name').drop(columns='District name')

In [15]:
final_df

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,856350,626997,566108,5512
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,1338474,972486,897970,8606
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,1484794,1183084,944555,13763
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,1716933,1571644,1297273,22411
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,1634726,1325715,1186028,19383
...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,2051541,1937304,2086432,1152019,934413,297716,5357
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,3627564,3476243,4055834,2177187,1878647,541169,7951
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,2653768,2513832,3480555,1878866,1601689,623729,12787
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1496996,1433119,1624905,1002058,622847,189889,3551
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,1551066,1456068,1489667,853495,636172,199307,2883

In [16]:
final_df['sex_ratio']=round((final_df['Female']/final_df['Male'])*100)

In [17]:
final_df['litracy_rate']=round((final_df['Literate']/final_df['Population'])*100)

In [18]:
final_df.drop(columns=['Male','Female','Literate'],inplace=True)

In [19]:
final_df

,State,District,Latitude,Longitude,District code,Population,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet,sex_ratio,litracy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,856350,626997,566108,5512,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,1338474,972486,897970,8606,98.0,57.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,1484794,1183084,944555,13763,100.0,64.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,1716933,1571644,1297273,22411,101.0,64.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,1634726,1325715,1186028,19383,100.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,1152019,934413,297716,5357,94.0,52.0
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,2177187,1878647,541169,7951,96.0,57.0
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,1878866,1601689,623729,12787,95.0,67.0
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1002058,622847,189889,3551,96.0,55.0
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,853495,636172,199307,2883,94.0,50.0

In [20]:
final_df.to_csv('india.csv',index=False)

In [21]:
list_of_states=list(final_df['State'].unique())
list_of_states.insert(0,'over all india')
list_of_states

['over all india',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [22]:
sorted(final_df.columns[5:])

['Female_Literate',
 'Households_with_Internet',
 'Housholds_with_Electric_Lighting',
 'Male_Literate',
 'Population',
 'litracy_rate',
 'sex_ratio']

In [23]:
import plotly.express as px

df =px.data.carshare()
fig = px.scatter_map(
    df,
    lat='centroid_lat',
    lon='centroid_lon',
    color='peak_hour',
    size='car_hours',
    color_continuous_scale=px.colors.cyclical.IceFire,
    size_max=15,
    zoom=10,
    map_style='carto-positron'
)

fig.show()

In [24]:
import plotly.express as px
df = px.data.carshare()
fig = px.scatter_map(df, lat="centroid_lat", lon="centroid_lon", color="peak_hour", zoom=10,map_style="open-street-map")
fig.show()

In [25]:
df[['centroid_lat', 'centroid_lon', 'peak_hour']].head()

   centroid_lat  centroid_lon  peak_hour
0     45.471549    -73.588684          2
1     45.543865    -73.562456         23
2     45.487640    -73.642767         20
3     45.522870    -73.595677         23
4     45.453971    -73.738946         19

In [26]:
print(df["centroid_lat"].min(), df["centroid_lat"].max())
print(df["centroid_lon"].min(), df["centroid_lon"].max())

45.448903185047335 45.61087892678886
-73.73894559925054 -73.5124596370787

In [27]:
center = {
    "lat": df["centroid_lat"].mean(),
    "lon": df["centroid_lon"].mean()
}

fig = px.scatter_map(
    df,
    lat="centroid_lat",
    lon="centroid_lon",
    color="peak_hour",
    center=center,
    zoom=10,
    map_style="open-street-map"
)

fig.show()

In [28]:
fig = px.scatter_map(
    df,
    lat="centroid_lat",
    lon="centroid_lon",
    color="peak_hour",
    center={"lat": 45.50, "lon": -73.60},
    zoom=10,
    map_style="open-street-map"
)

fig.show()

In [29]:
center={'lat':final_df['Latitude'].mean(),'lon':final_df['Longitude'].mean()}
fig=px.scatter_map(final_df,lat='Latitude',lon='Longitude',center=center,zoom=2.5,map_style='carto-positron')
fig.show()