In [1]:
import pandas as pd

In [2]:
pd.read_excel('subs.xlsx')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [3]:
pd.read_excel('bollywood.xlsx')

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [4]:
pd.read_excel('bollywood.xlsx',index_col='movie')

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [5]:
pd.read_excel('two_sheet.xlsx')

   student_id   name  class    city
0         101   Amit      6   Patna
1         102  Priya      6    Gaya
2         103  Rahul      7   Delhi
3         104   Neha      6   Patna
4         105   Sana      7  Ranchi

In [6]:
pd.read_excel('two_sheet.xlsx',sheet_name=None)

{'Students':    student_id   name  class    city
 0         101   Amit      6   Patna
 1         102  Priya      6    Gaya
 2         103  Rahul      7   Delhi
 3         104   Neha      6   Patna
 4         105   Sana      7  Ranchi,
 'Marks':    student_id  maths  science  english
 0         101     85       79       88
 1         102     92       90       86
 2         103     76       81       74
 3         104     88       84       91
 4         105     95       93       89}