In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('startup_funding.csv')
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [3]:
df.drop(columns=['Remarks'],inplace=True)

In [4]:
df.set_index('Sr No',inplace=True)

In [5]:

df.rename(columns={
    'Date dd/mm/yyyy':'date',
    'Startup Name':'startup',
    'Industry Vertical':'vertical',
    'SubVertical':'subvertical',
    'City  Location':'city',
    'Investors Name':'investors',
    'InvestmentnType':'round',
    'Amount in USD':'amount'

},inplace=True)

In [6]:
df['amount']=df['amount'].fillna('0')

In [7]:
df['amount']=df['amount'].str.replace(',','')
df['amount']=df['amount'].str.replace('undisclosed','0')
df['amount']=df['amount'].str.replace('Undisclosed','0')
df['amount']=df['amount'].str.replace('unknown','0')

In [8]:
df=df[df['amount'].str.isdigit()]

In [9]:
df['amount']=df['amount'].astype('float')

In [10]:
def to_inr(dollor):
     inr=dollor*95
     return inr/10000000

In [11]:
df['amount']=df['amount'].apply(to_inr)

In [12]:
df['date']=df['date'].str.replace('05/072018','05/07/2018')

In [13]:
df['date']=pd.to_datetime(df['date'],format='%d/%m/%Y',errors='coerce').dt.strftime('%d/%m/%Y')

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 3029 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3023 non-null   str
 1   startup      3029 non-null   str
 2   vertical     2858 non-null   str
 3   subvertical  2104 non-null   str
 4   city         2849 non-null   str
 5   investors    3005 non-null   str
 6   round        3027 non-null   str
 7   amount       3029 non-null   float64
dtypes: float64(1), str(7)
memory usage: 543.0 KB

In [15]:
df=df.dropna(subset=['date','startup','vertical','city','investors','round','amount'])

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 2819 entries, 1 to 2873
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         2819 non-null   str
 1   startup      2819 non-null   str
 2   vertical     2819 non-null   str
 3   subvertical  2078 non-null   str
 4   city         2819 non-null   str
 5   investors    2819 non-null   str
 6   round        2819 non-null   str
 7   amount       2819 non-null   float64
dtypes: float64(1), str(7)
memory usage: 513.6 KB

In [17]:
df.to_csv('startup_cleaned.csv',index=False)

In [21]:
sorted(set(df['investors'].str.split(',').sum()))

['',
 ' & Others',
 ' 100 Co-founders Lab and others.',
 ' 122 West Ventures',
 ' 1Crowd',
 ' 3ONE4 Capital Advisors',
 ' 3one4 Capital',
 ' 3one4 Capital Advisors LLP',
 ' 500 Start-Ups',
 ' 500 Startups',
 ' 500 Startups & Other HNIs',
 ' 50K Ventures & others',
 ' 91SpringBoard',
 ' 91springboard',
 ' ABB Technology Ventures',
 ' ABCOM Investments',
 ' AECAL',
 ' AET Fund',
 ' AL Nour International Holdings and Mark V Investments',
 ' ASP Consulting',
 ' AVN Business Solutions',
 ' Aarin Capital',
 ' Aarin Capital & Others',
 ' Aaruha Technology Fund',
 ' Abaran Deep',
 ' Abhai S. Rao',
 ' Abhay Singhal',
 ' Abhijit Bhandari',
 ' Abhinav Patodia',
 ' Abhinav Sinha',
 ' Abhishek Acharya',
 ' Abhishek Goyal',
 ' Abhishek Gupta',
 ' Abhishek Jain',
 ' Abhishekh Goyal',
 ' Abstract Ventures',
 ' Abu Farhan Azmi',
 ' Accel',
 ' Accel India',
 ' Accel Partner',
 ' Accel Partners',
 ' Accel Partners & Others',
 ' Accel Partners & Raghunandan Gangappa',
 ' Accel Partners & existing investors',
 ' Accel Partners RNT Associates',
 ' Accel Partners and G Raghunandan',
 ' Accel Partners and IDG Ventures',
 ' Accel Partners and Saama Capital',
 ' Accel Partners and Tiger Global Management.',
 ' Accion',
 ' Accion Venture Lab',
 ' Acumen Fund',
 ' Adam D\\\\xe2\\\\x80\\\\x99Angelo',
 ' Adi Saravanan',
 ' Adil Allana',
 ' Aditya Agarwal',
 ' Aditya Aggarwal',
 ' Aditya Dev Sood',
 ' Aditya Malik & Others',
 ' Aditya Singh',
 ' Aditya Vazirani',
 ' Aditya Verma',
 ' Aditya Vij',
 ' AdvantEdge Partners',
 ' Adveq Management',
 ' Afsal Salu',
 ' Aijaz Saleem',
 ' Ajay Bhatia',
 ' Ajay Data',
 ' Ajay Lakhotia',
 ' Ajay Modani',
 ' Ajay Sarupria',
 ' Ajeet Khurana',
 ' Ajeet Khurana & others',
 ' Akash Bhavsar',
 ' Akash Garg',
 ' Akatsuki and Incubate Fund from Japan and Better Capital AngelList syndicate.',
 ' Akusa Holdings',
 ' Alagu Periyannan and Karthee Madasamy',
 ' Alexander Bruehl',
 ' Alfa Capital',
 ' Alok Divatia',
 ' Alok Goel',
 ' Alok Mittal',
 ' Alok Mittal & others',
 ' Alok Mittal and Sachin Bhatia',
 ' Alok Sharma',
 ' Alok Srivastava',
 ' Aloke Bajpai',
 ' Alphabet\\\\xe2\\\\x80\\\\x99s growth investment arm Capital G and Axis Bank',
 ' Altimeter Capital',
 ' Alto Partners',
 ' Amanpreet Bajaj',
 ' Amar Arsikere',
 ' Amaya Capital LLP',
 ' Ambarish Gupta',
 ' Ambarish Ray',
 ' Ambi Parameswaran',
 ' Ambiga Dhiraj',
 ' Ameera Shah',
 ' Amereus Group',
 ' American Express',
 ' American Express Ventures',
 ' Amit Agrawal',
 ' Amit Banati',
 ' Amit Banka',
 ' Amit Dey',
 ' Amit Gupta',
 ' Amit Jindal',
 ' Amit Khanna',
 ' Amit Khanna (LetsVenture)',
 ' Amit Kharbanda',
 ' Amit Manocha',
 ' Amit Nagar',
 ' Amit Nanavati',
 ' Amit Patni',
 ' Amit Ranjan',
 ' Amit Ranjan & others',
 ' Amit Rathore',
 ' Amit Sandill',
 ' Amit Singal',
 ' Amit Sinha',
 ' Amitpal Bhutani',
 ' Amiya Pathak',
 ' Amrendra Reddy and Manish Satnaliwala.',
 ' Amrish Kumar',
 ' Amrish Rau',
 ' Anand Chandrasekaran',
 ' Anand Kumar',
 ' Anand Ladsariya',
 ' Anand Mahindra',
 ' Anand Rajaraman',
 ' Anand Sankeshwar',
 ' Anand Singh',
 ' Ananda Kallugadde',
 ' Anandbir Singh',
 ' Ananth Narayanan',
 ' Anbu Pandian',
 ' Andre Hoffman',
 ' Aneesh Reddy',
 ' Aneesh Reddy & Teruhide Sato',
 ' Angie Mahtaney',
 ' Anil Chopra',
 ' Anil Gelra',
 ' Anil Jaggia',
 ' Anil Jain',
 ' Anindya Ghose',
 ' Anirudh Damani',
 ' Anirudh Rastogi',
 ' Anirudh Sheth',
 ' Anish K',
 ' Anisha Mittal',
 ' Anita Gupta',
 ' Anita Hassanandani',
 ' Anjali Bansal',
 ' Anjani Prasad',
 ' Ankit Aditya',
 ' Ankit Bhati',
 ' Ankit Nagori',
 ' Ankit Sharma and others',
 ' Ankur Capital',
 ' Ankur Singla',
 ' Ankur Warikoo',
 ' Ankush Gupta',
 ' Ankush Nijhawa',
 ' Ankush Nijhawan',
 ' Ankush Saigal',
 ' Anoop Goyal',
 ' Anoop Hingorani',
 ' Anshoo Gaur',
 ' Anshu Bahadur',
 ' Anshu Sharma',
 ' Anshul Jindal',
 ' Anshuman Das',
 ' Ant Financial',
 ' Anthil Ventures & others',
 ' Anthill Scale Ventures',
 ' Anthill Ventures',
 ' Anubhav Verma',
 ' Anuj Agrawal',
 ' Anuj Golecha',
 ' Anuj Gupta',
 ' Anuj Puri',
 ' Anuj Sanghi',
 ' Anuj Srivastava',
 ' Anupam Mittal',
 ' Anupam Mittal & other marquee investors',
 ' Anupam Mittal & others',
 ' Anupam Tyagi',
 ' Anurag Gupta',
 ' Anurag Srivastava',
 ' Apoletto',
 ' Apoletto Managers',
 ' Apoorv Ranjan Sharma',
 ' Apoorva Patni',
 ' Appliyifi',
 ' Aprameya',
 ' Aprameya Radhakrishna',
 ' Aprameya Radhakrishnan',
 ' Apurva Chamaria',
 ' Apurva Salapuria',
 ' Apurva Salarpuria',
 ' Aqeel Ahmed',
 ' Arathi Krishna',
 ' Aravind Sanka',
 ' Arihant Patni',
 ' Arihant Patni of Patni Family Office',
 ' Arjun Malhotra',
 ' Arjun Mehta',
 ' Arjun Sharmaa',
 ' Arjun and Rohan Malhotra',
 ' Arkas Industries',
 ' Artha India Ventures',
 ' Arthavida Ventures',
 ' Artiman Ventures',
 ' Arts Alliance',
 ' Arun Garg',
 ' Arun Khanna',
 ' Arun Malhotra',
 ' Arun Sarin',
 ' Arun Tadanki',
 ' Arun Venkatachalam',
 ' Aruna Ganesh Ram',
 ' Arvind Uppal',
 ' Ascent Capital',
 ' Aseem Sood',
 ' Ashim Mehra',
 ' Ashish Agrawal',
 ' Ashish Chand',
 ' Ashish Dev Kapur',
 ' Ashish Dhawan',
 ' Ashish Goenka',
 ' Ashish Goenka & Others',
 ' Ashish Gupta',
 ' Ashish Hemrajani',
 ' Ashish Lakhanpal',
 ' Ashish Toshniwal',
 ' Ashish Tulsian',
 ' Ashneer Grover',
 ' Ashvin Chadha',
 ' Asian Healthcare fund',
 ' Aspada',
 ' Aspada Investment',
 ' Aspada Ventures',
 ' Astarc Ventures',
 ' Atul Goel',
 ' Atul Nishar',
 ' Atul Phadnis',
 ' Augment Ventures',
 ' Avnish Mehra',
 ' Avtar Monga',
 ' Axan Partners',
 ' Axan Venture',
 ' Axilor Partners',
 ' Axilor Ventures',
 ' Axilor Ventures and Binny Bansal',
 ' Axis Bank',
 ' Axis Capital',
 ' Axis Capital & Others',
 ' Axon Partners',
 ' Azmul Haque',
 ' B Capital',
 ' BEENEXT',
 ' BEENEXT Ventures',
 ' BVR Mohan Reddy',
 ' Badal Malick',
 ' Balaji Prabhakar',
 ' Balamurugan Mani',
 ' Bamboo Capital Partners',
 ' Bank to the Future and Funders Club',
 ' Barkawi Holdings GmbH',
 ' Basab Pradhan',
 ' Batlivala & Karani Securities',
 ' Bedrock Ventures',
 ' BeeNext',
 ' Beehive Capital Advisor',
 ' Beenext',
 ' Beenext Ventures',
 ' Beenextan investment fund',
 ' Beenos',
 ' Beenos Asia',
 ' Behram Vakil and Jerxis Vandrevala',
 ' Bennett Coleman & Co. Ltd',
 ' Berggruen Holdings',
 ' Bertelsmann India',
 ' Bertelsmann India Investments',
 ' Bertelsmann India Investments Norwest Venture Partners.',
 ' Bessemer Venture Partners',
 ' Bharat Gupta',
 ' Bharat Kedia',
 ' Bharat Sheth',
 ' Bharat Vijay',
 ' Bharti Enterprises',
 ' Bhavish Aggarwal',
 ' Bhupen Shah & Others',
 ' Bhupender Singh',
 ' Big Data Investments B.V',
 ' Bijou Kurien',
 ' Bill & Melinda Gates Foundation',
 ' Binny Bansal',
 ' Biz Stone',
 ' BizReach',
 ' Blacksoil',
 ' Blacksoil and Kalaari Capital',
 ' Blue Cloud Ventures',
 ' Blue Fog Capital',
 ' Blume Ventures',
 ' Blume Ventures & IvyCap Ventures',
 ' Blume Ventures & Others',
 ' Blume Ventures & Vaibhav Domkundwar',
 ' Blume Ventures & others',
 ' Blume Ventures and Innoven Capital.',
 ' Blume Ventures and Ujama',
 ' Blume Ventures.',
 ' Blume ventures',
 ' Bobby Reddy',
 ' Boillot Family Trust',
 ' Bold Ventures',
 ' BookMyShow)',
 ' Boost VC',
 ' BrahmaX Ventures',
 ' Brand Capital',
 ' Bunny Bansal & other investors',
 ' Burda Principal Investments',
 ' C31 Ventures',
 ' CCavenue',
 ' CDC Group',
 ' CRV',
 ' CSC Upshot & Angel investors',
 ' Calcutta Angels',
 ' Canaan Partners',
 ' Capier Investments',
 ' CapitalG',
 ' Capricorn Investment Group',
 ' Capricorn Investment and IFC',
 ' Caspian and Hivos-Triodos Fund',
 ' Catamaran Ventures',
 ' Chanakya Hridaya',
 ' Chandru Badrinarayanan',
 ' Chavi Jafa',
 ' Cheetah Mobile',
 ' Chennai Angels',
 ' Chetan Bhagat',
 ' Chidambaram Palaniappan',
 ' Chiratae Ventures',
 ' Chiratae Ventures (formerly IDG Ventures)',
 ' Cisco Investments',
 ' Cisco Ventures',
 ' Citi Ventures',
 ' Citrus Payments',
 ' Coatue Management',
 ' Coleman and Co. Ltd (BCCL)',
 ' Coleman and Company Ltd',
 ' Coleman and Company Ltd (BCCL)',
 ' Contrarian Capital',
 ' Contrarian Capital India Partners',
 ' Contrarian Vriddhi Fund',
 ' Corvus Ventures',
 ' Cota Capital',
 ' Currae Healthtech Fund',
 ' Cyber Carrier VC',
 ' CyberAgent Ventures',
 ' DG Incubation',
 ' DG Ventures India',
 ' DSG Consumer Partners',
 ' DSG Consumer Partners and Venture Nursery',
 ' DST Global',
 ' DST Partners and RPS Ventures',
 ' Dalip Pathak',
 ' Dalip Pathak and Others',
 ' Daljit Singh',
 ' Darius Pandole',
 ' Darrin Capital',
 ' Darshak Shah',
 ' Darshan Upadhyay',
 ' Das Capital and IT Farm',
 ' Daud Ali',
 ' Daud Ali and others',
 ' DeVry Inc',
 ' Deep Kalra',
 ' Deepak Chokhani',
 ' Deepak Ghaisas',
 ' Deepak Jain',
 ' Deepak Natraj',
 ' Deepak Sharma',
 ' Deepak Singh',
 ' Deepinder Goyal',
 ' Delhivery',
 ' Dena',
 ' Deobrat Singh',
 ' Deshe Holdings',
 ' Deshpande Foundation',
 ' Deutsche Telekom Strategic Investments (DTSI)',
 ' Devendra Rane',
 ' Devendra Reddy',
 ' Dewan Housing Finance Corp',
 ' Dexter Angel Circle',
 ' Dheerag Jain',
 ' Dheeraj Jain',
 ' Dheeraj Mehta & Others',
 ' Dhiraj Rajaram',
 ' Dhruv Chitgopekar',
 ' Diaz Nesamoney',
 ' Didi Kuaidi',
 ' Digital Currency Group',
 ' Digital Garage',
 ' Digital Garage Inc',
 ' Dileep Nath',
 ' Dilip Khandwelwal from SAP Labs India',
 ' Dinesh Agarwal',
 ' Dinesh Kundu & others',
 ' Dinesh Mittal',
 ' Dinesh R. Challa',
 ' Dino Morea',
 ' Divyesh Shah',
 ' Doreswamy Nandkishore',
 ' Dr Paresh Doshi',
 ' Dr V Ravinder',
 ' Dr. Aniruddha Malpani',
 ' Dr. Apoorv Ranjan Sharma',
 ' Dr. Pramath Raj Sinha',
 ' Dr. Prasad Kaipa',
 ' Dr. Ranjan Pai',
 ' Dr. Ritesh Malik',
 ' Draper Associates',
 ' Draper Fisher Jurvetson',
 ' Draphant Consultants',
 ' Dream Incubator',
 ' Dreamweaver Investments',
 ' E-City VEntures Atul Goel',
 ' E.ON',
 ' EDBI',
 ' Edelweiss Private Equity',
 ' Edelweiss and Beenext',
 ' Eight Innovate',
 ' Eight Roads Ventures',
 ' Eight Roads Ventures India',
 ' Electronic Development Fund',
 ' Elevar Equity',
 ' Elevar Equity and Accel Partners',
 ' Elevate Sports',
 ' Emergent Ventures',
 ' Emergent Ventures India',
 ' Emergent Ventures and Y Combinator',
 ' Empire Angels',
 ' Endiya Partners',
 ' Entrepreneurs India',
 ' Esvee Technologies Inc',
 ' Eureka Forbes Ltd',
 ' European investment fund',
 ' Evan Lim',
 ' Excelsior Investments',
 ' Exfinity Venture Partners & Others',
 ' Exfinity Ventures',
 ' Existing investors',
 ' F-Prime Capital Partners',
 ' FAO Ventures',
 ' FIL Capital Management',
 ' FJ Labs',
 ' Faering Capital',
 ' Falcon Edge',
 ' Falcon Edge Capital',
 ' Faraz Khan',
 ' Farhan Naqvi',
 ' Farooq Adam Mukadam',
 ' Fauzan Rahim',
 ' Fenqile',
 ' Fidelity Biosciences',
 ' Fidelity Growth Partners',
 ' Fidelity Growth Partners India',
 ' Fireside Ventures',
 ' Flipkart',
 ' Florintree Advisors',
 ' Fortisure Ventures',
 ' Fosun RZ Capital',
 ' Foundation Capital',
 ' Founder Collective',
 ' Founders Fund',
 ' Foxconn',
 ' Foxconn Technology Group',
 ' Franchise India Brands',
 ' Fred Khosravi',
 ' FreshMenu)',
 ' Frontline Strategy',
 ' Fullerton India Credit Company Ltd',
 ' Fundnel',
 ' Fusion Tech Ventures',
 ' Fusiontech Ventures & Others',
 ' G Ravishankar',
 ' GFC',
 ' GHV',
 ' GHV Accelerator',
 ' GREE Ventures',
 ' GREE Ventures and Summit Media',
 ' GSF and Other angel investors',
 ' GVFL',
 ' Gabriel Investments',
 ' Gagan Dugal',
 ' Gagan Goyal',
 ' Gagan Hasteer ',
 ' Ganpat Singhvi',
 ' Gaurav Agarwal',
 ' Gaurav Bhalotia',
 ' Gaurav Bhatnagar',
 ' Gaurav Bhogle',
 ' Gaurav Dalmia',
 ' Gaurav Gupta',
 ' Gaurav Lochan',
 ' Gaurav Luniya',
 ' Gaurav Marya',
 ' Gaurav Munjal',
 ' Gaurav Sharma',
 ' Gaurav Suri and Ankit Kesarwani',
 ' Gaurav Vats',
 ' Gautam Chhaochharia',
 ' Gautam Gandhi',
 ' Gautam Ivatury',
 ' Gautam Sinha',
 ' Girish Mathrubootham',
 ' Girish Mathrubootham &\\\\xc2\\\\xa0 Group of other Angel investors',
 ' Girish Matrubootham',
 ' Girish Reddy',
 ' Girnar Software',
 ' Global Founders Capital',
 ' Globeinvestor',
 ' Globevestor',
 ' Globevestor & others',
 ' Goa',
 ' Gokul Rajaram',
 ' Goldbell Group',
 ' Goldman Sachs',
 ' Google Capital',
 ' Google Capital & Accel Partners',
 ' Govind Rajan & Others',
 ' Grace Capital Ventures',
 ' Great Oaks Ventures',
 ' Green Shots Capital',
 ' Greenoaks Capital',
 ' Greenoaks Capital Partners',
 ' Grey Orange',
 ' Grey Orange Robotics',
 ' Greycroft',
 ' Greycroft Partners',
 ' GrowX',
 ' GrowX Ventures',
 ' Gulpreet Kohli',
 ' Gund Investment',
 ' Gurmeet Chahal & Others',
 ' Gurpreet Singh & others',
 ' Gyanendra Singh',
 ' H C Jain',
 ' HDFC',
 ' HDFC Asset Management',
 ' HR Fund',
 ' Hack VC',
 ' Haitong Securities',
 ' Haresh Chawla',
 ' Harminder Sahani',
 ' Harmony Partners',
 ' Harpreet Singh Grover',
 ' Harsh Kundra',
 ' Harsh Mariwala',
 ' Harvard Angels',
 ' HealthQuad',
 ' HealthQuad and Fireside Ventures',
 ' Healthsquad',
 ' Helion Advisors',
 ' Helion Venture',
 ' Helion Venture Partners',
 ' Helion Ventures',
 ' Hemant Kanakia',
 ' Hemant Kaul',
 ' Hemant Luthra',
 ' Herb Madan',
 ' Hercules Capital',
 ' Hermes Group',
 ' Hero Electronix\\\\xe2\\\\x80\\\\x99s corporate financing arm',
 ' Hero Enterprise',
 ' Hetal Sonpal',
 ' Hillhouse Capital',
 ' Himanshu Aggarwal',
 ' Himanshu Aggrawal',
 ' Hinduja Group',
 ' Hinduja Leyland Finance and IntelleGrow',
 ' Hiro Mashita',
 ' Hirokazu',
 ' Hitesh Gupta',
 ' Hitesh Oberoi',
 ' Holtzbrink Ventures',
 ' Horizons Ventures',
 ' Hornbill Orchid India Fund',
 ' Horseferry',
 ' Hrishi Oberoi',
 ' Hrishikesh Parandekar',
 ' Huang Wei',
 ' Hyderabad Angels',
 ' IA Venture Strategies Fund II LP',
 ' IAN Fund',
 ' IDFC-Parampara Capital',
 ' IDFC-Parampara Fund',
 ' IDG Venture',
 ' IDG Ventures',
 ' IDG Ventures & Advantedge fund',
 ' IDG Ventures & Indian Angel Network',
 ' IDG Ventures India',
 ' IFC',
 ' IFMR',
 ' IIFL',
 ' IIFL Wealth',
 ' ILearnFinance Academy Pvt. Ltd.',
 ' IMJ Investment Partners',
 ' IMM Investment',
 ' ITW Digital',
 ' Ideation Initiative Pvt. Ltd',
 ' Ignition Partners',
 ' Imanpreet Singh Arora',
 ' InMobi',
 ' Inc',
 ' Inc95 Consulting',
 ' Incubation Foundation (SIIF)',
 ' India Alternatives',
 ' India Innovation Fund India Venture Partners',
 ' India Internet Fund',
 ' India Quotient',
 ' Indian Angel Network',
 ' Indian Angel Network (IAN)',
 ' Individual Investors',
 ' Indus Age Partners',
 ' Infocomm Development Authority of Singapore',
 ' Infocomm Investments',
 ' Infosys Innovation Fund',
 ' Infuse Ventures',
 ' Innogy',
 ' Innov8',
 ' Innov8 founder Ritesh Malik',
 ' Innoven Capital',
 ' Intel Capital',
 ' Intel Capital & Kae Capital',
 ' IntelleGrow',
 ' Intellecap Impact Investment Network',
 ' International Finance Corporation (IFC)',
 ' Internet Group',
 ' Inventus Capital',
 ' Inventus Capital Partners',
 ' Investment AB Kinnevik',
 ' Investopad',
 ' IvyCap Ventures',
 ' J.P. Bhatt',
 ' JAFCO Asia',
 ' JLL',
 ' JM Financials and MEMG',
 ' Jagdish & Sandeep Mehta Family Office',
 ' Jagdish Kumar',
 ' Jaikumar Nair',
 ' Jairaj Singh',
 ' Jamil Khatri',
 ' Jarett Posner',
 ' Jason Hirschhorn',
 ' Jaspreet Bindra',
 ' Jatin Aneja',
 ' Jay Sethuram',
 ' Jay Srinivasan',
 ' Jayant Davar',
 ' Jayant Kadambi',
 ' Jayesh Parekh',
 ' Jayesh Shah',
 ' Jaysukh Sapra',
 ' Jeevanandhan Rajagopal',
 ' Jeroen Mensen',
 ' Jim Schimdktke',
 ' Jitendra Gupta',
 ' Jitendra Gupta & Others',
 ' Joby Babu',
 ' John Katzman',
 ' Jonathan Boutelle',
 ' Josh Talks founders Supriya Paul and Shobha Banga',
 ' Jr. Millennium Trust',
 ' Jungle Venture Partners',
 ' Jungle Ventures',
 ' Jungle Ventures & Bessemer Venture Partners',
 ' Jyoti Bansal',
 ' K Ganesh',
 ' KCK Global & Others',
 ' KK Mehra',
 ' Kae Capital',
 ' Kae Capital & Others',
 ' Kalaari Capital',
 ' Kalaari Capital and IDG Ventures India',
 ' Kalaari Capital and Inventus Capital',
 ' Kalaari Capital and Others',
 ' Kalaari Capital and Private equity firm Multiples Alternate Asset Management',
 ' Kalpana Tatavarti',
 ' Kamal Bansal',
 ' Kamal Chabra',
 ' Kamal Kothari',
 ' Kamal Puri',
 ' Kanchan Ghoshal',
 ' Kanwaljit Singh',
 ' Kapil Hetamsaria',
 ' Karan Chellani',
 ' Karan Maheshwari',
 ' Karthee Madasamay',
 ' Kartik Hosanagar',
 ' Kashyap Deorah',
 ' Keiretsu Forum & Others',
 ' Keith Rodricks',
 ' Keshav Sanghi',
 ' Khattar Holdings',
 ' Khazanah Nasional Berhad',
 ' Khosla Impact',
 ' Khosla Ventures',
 ' Kima Ventures',
 ' Kinzon Capital',
 ' Kiran Deshpande',
 ' Kiran Mazumdar-Shaw',
 ' Kiran Shetty',
 ' Kishor Ganji',
 ' Kishore Ganji',
 ' Kishore Kumar',
 ' Kiyohiro Sugashita',
 ' Knoll Ventures and others',
 ' Konly Venture',
 ' Kris Gopalakrishnan',
 ' Krish Seshadri',
 ' Krishan Gupta & Others',
 ' Krishna Jhunjhunwaala',
 ' Krishna Jhunjhunwala',
 ' Krishna Mehra',
 ' Krishnakumar Nataraj',
 ' Krishnakumar Natarajan',
 ' Krit Sankalp',
 ' Kshitij Arora',
 ' Kshitij Jain',
 ' Kumar Shwetabh',
 ' Kumar Vembu',
 ' Kunal Bahl',
 ' Kunal Khattar',
 ' Kunal Shah',
 ' Kunal Shah & Sandeep Tandon',
 ' Kunal Shah and Manish Patel.',
 ' L.D Sharma',
 ' LG Chandrasekhar',
 ' LGT Impact',
 ' LGT Impact Ventures',
 ' LN Buddharaju',
 ' LV Prasad',
 ' Lakshmi Narayanan',
 ' Lalit Mangal',
 ' Larry Braitman',
 ' Lasmer NV',
 ' Lead Angels',
 ' Lead Angels & Others',
 ' Lead Angels Group & Others',
 ' LeapFrog Investments',
 ' Learn Capital',
 ' Leo Wang Sangeeth Ram',
 ' Leon Seynave',
 ' Let\\\\xe2\\\\x80\\\\x99s Venture',
 ' LetsVenture',
 ' LetsVenture & Others',
 ' LetsVenture investors',
 ' Li Jian',
 ' Liberty Media',
 ' LightStreet',
 ' Lightbox',
 ' Lightbox Expansion Fund',
 ' Lightbridge Partners & Kairos',
 ' Lightspeed India',
 ' Lightspeed US',
 ' Lightspeed Venture Partners',
 ' Lightspeed Ventures',
 ' Likemind Ventures',
 ' Line Corp',
 ' Liquid 2 Ventures',
 ' Littlerock',
 ' Lok Capital',
 ' Lomesh Agarwal',
 ' Low Carbon Enterprise Fund',
 ' Lumina Datamatics',
 ' Lumis Partners',
 ' M & S partners',
 ' M George Oommen',
 ' M&S Partners',
 ' M&S Partners & others',
 ' MAPE Advisory Group',
 ' MEMG CDC',
 ' MEMG Family Office',
 ' MGV',
 ' MJ Aravind',
 ' MMY co-Founder',
 ' Madhusudan E',
 ' Madhusudhan Jujare & Others',
 ' Madhusudhan Kannan',
 ' Mahavir Pratap Sharma',
 ' Mahavir Sharma',
 ' Mahendra Doshi',
 ' Mahesh Kothurkar',
 ' Mahesh Murthy',
 ' Maheshwar Peri',
 ' Maheshwari Investments Pvt Ltd',
 ' Maiden Lane Ventures',
 ' MakeMyTrip',
 ' Malvinder and Shivinder Singh',
 ' Mamoru Taniya',
 ' Mandar Mhatre',
 ' Mandhian family & Others',
 ' Manickam Mahalingam',
 ' Maninder Gulati',
 ' Manish Amin',
 ' Manish Dhingra',
 ' Manish Dugar',
 ' Manish Gandhi',
 ' Manish Kheterpal',
 ' Manish Prasad',
 ' Manish Shah',
 ' Manish Singhal',
 ' Manish Vij',
 ' Manisha Gupta',
 ' Manoj Varghese',
 ' Mantra Ventures',
 ' Manvinder Singh Banga',
 ' Mape Advisory Group',
 ' March Capital',
 ' Mariwala family',
 ' Mathew Cyriac',
 ' Mato Peric',
 ' Mato Peric & Others',
 ' Matrix Partners',
 ' Matrix Partners India',
 ' Matrix Partners India and Zodius Capital',
 ' Maverick Capital Ltd and HBM Healthcare Investments Ltd',
 ' Maverick Capital Ventures',
 ' Mayank Bhangdia',
 ' Mayank Mittal & Others',
 ' Mayank Singhal',
 ' Mayfield',
 ' Mayfield & Others',
 ' Mayfield Capital',
 ' Mayfield India',
 ' Mayfield Ventures',
 ' Mayur Abhaya',
 ' MediAssist',
 ' MediaTek',
 ' Meet Kanodia',
 ' Mekin Maheshwari',
 ' MeraEvents.',
 ' Michael & Susan Dell Foundation',
 ' Michael Carlos',
 ' Michael Herzig',
 ' Michael Marks',
 ' Michael and Susan Dell Foundation',
 ' Micro venture capital firm GEMS Partners and Others',
 ' Micromax',
 ' Micromax Informatics',
 ' Mike Galgon',
 ' Mike Shah',
 ' Milind Chaudhary',
 ' Milind Sarwate',
 ' Milliways Ventures',
 ' Mistletoe',
 ' Mitali Pawar',
 ' Miten Mehta',
 ' Mitesh Shah',
 ' Mohan Alexander',
 ' Mohandas Pai',
 ' Mohandas Pai. Pallav Nadhani',
 ' Mohit Agarwal',
 ' Mohit Gupta',
 ' Mohit Satyan',
 ' Mohit Satyanand',
 ' Mohit Satyanand & others',
 ' Mohit Saxena',
 ' Moksh Sports Ventures',
 ' Mount Nathan Advisors',
 ' Mountain Pine Capital',
 ' Mousse Partners',
 ' Mr. Praveen Someshwar',
 ' Mridul Upreti',
 ' Mukul Singhal',

In [26]:
df[df['investors'].str.contains(' IDG Ventures')].head()[['date','startup','vertical','city','round','amount']]

,date,startup,vertical,city,round,amount
Sr No,,,,,,
102,13/04/2019,Tripoto,Social Media,New Delhi,Series B,34.118063
259,02/05/2018,Bizongo,Consumer Internet,Mumbai,Private Equity,209.000000
310,26/04/2018,POPxo,Technology,Delhi,Private Equity,52.250000
505,21/11/2017,Heckyl,Technology,Mumbai,Private Equity,25.650000
528,05/10/2017,Little Black Book,Consumer Internet,New Delhi,Private Equity,9.500000

In [28]:
df[df['investors'].str.contains(' IDG Ventures')].groupby('startup')['amount'].sum().sort_values(ascending=False)

startup
Lenskart                 570.000000
CureFit                  237.500000
Bizongo                  209.000000
Curefit                  142.500000
Xpressbees               118.750000
FirstCry.com              95.000000
POPxo                     81.700000
\\xc2\\xa0CloudCherry     57.000000
Sigtuple                  55.100000
Aasaanjobs                47.500000
RentMojo                  47.500000
PlaySimple                38.000000
Tripoto                   34.118063
Active.ai                 28.500000
Heckyl                    25.650000
Cloudcherry Analytics      9.500000
Little Black Book          9.500000
Name: amount, dtype: float64